version: 1.0.0
workspace: null
config_path: D:\deep\backend\config.yaml
model:
  type: openai
  api_key: 
  endpoint: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: qwen-plus
user_model:
  type: openai
  api_key: 
  endpoint: https://api.deepseek.com/v1
  model: deepseek-chat
vision_model:
  type: openai
  api_key: 
  endpoint: https://api.moonshot.cn/v1
  model: moonshot-v1-8k-vision-preview
server:
  host: 127.0.0.1
  port: 8000
  frontend_port: 5173
